[project]
name = "osw-data"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10, <3.13"
dependencies = [
    "numpy>=1.9.3",
    "pydantic>=2.7",
    "pyyaml>=6.0.2",
    "rich>=13.9.4",
    "types-PyYAML>=6.0.2"
]


[tool.hatch.build.targets.wheel]
packages = ["src/osw_data"]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
