[project]
name = "autolibra-core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "jinja2>=3.1.5",
    "numpy>=1.9.3",
    "polars>=1.19.0",
    "pydantic-ai>=0.0.18",
    "pydantic>=2.7",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
    "rich>=13.9.4",
    "types-requests>=2.32.0.20241016",
    "osw-data>=0.0.1",
]

[project.optional-dependencies]
webarena = [
    "gdown>=5.2.0",
    "pillow>=11.1.0",
]
sotopia = [
    "huggingface-hub>=0.27.1",
]

[tool.hatch.build]
include = ["src/autolibra_core/templates/*.j2"]

[tool.hatch.build.targets.wheel]
packages = ["src/autolibra_core"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
