[project]
name = "osw-eval-core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "h5py>=3.12.1",
    "numpy>=2.2.1",
    "polars>=1.19.0",
    "pydantic>=2.10.5",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
    "rich>=13.9.4",
    "types-requests>=2.32.0.20241016",
]

[project.optional-dependencies]
webarena = [
    "gdown>=5.2.0",
    "pillow>=11.1.0",
]

[tool.hatch.build.targets.wheel]
packages = ["src/osw_eval_core"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
